export default  {
    Categories:[
        {
        _id:'1',
        name:' Apex Legend',
        image:'/images/fg1.jpg',
        developer:'Developed By:Respawn Entertainment',
        price:0,
        category:"Top Free",
        buy:'BUY',
        ratings:4.5,
        description:'Apex Legend is an Action packed multiplayer game with wide variety of weapons and fun to play maps,appealing graphics and breathtaking duels.',
        reviews1:'Raj:(This game is very good) 5 stars',
        reviews2:'Aishwariya:(Very nice game) 5 stars',
        reviews3:'Arjun:(needs bit of improvement) 4 stars',
        reviews4:'Vaishali:(Good game) 4 stars',
        video:'/videos/vid1.mp4',
        countInStock:6,
    },
    {   
        _id:'2',
        name:' COD Warzone',
        image:'/images/fg5.jpg',
        developer:'Developed By:Activision',
        category:"Top Paid",
        price:40,
        buy:'BUY',
        ratings:4.6,
        description:'Warzone is a new, massive combat experience with up to 150 players from the world of Call of Duty: Modern Warfare and is free-to-play for everyone.',
        reviews1:'Raj:(This game is very good) 5 stars',
        reviews2:'Aishwariya:(Very nice game) 5 stars',
        reviews3:'Arjun:(needs bit of improvement) 4 stars',
        reviews4:'Vaishali:(Good game) 4.4 stars',
        video:'/videos/vid1.mp4',
        countInStock:3,
    },
    {
        _id:'3',
        name:' Minecraft',
        image:'/images/fg3.jpg',
        developer:'Developed By:Mojang Studios',
        category:"Top Paid",
        price:20,
        buy:'BUY',
        ratings:4.3,
        description:'Minecraft is a video game in which players create and break apart various kinds of blocks in three-dimensional worlds. The games two main modes are Survival and Creative. In Survival, players must find their own building supplies and food. They also interact with blocklike mobs, or moving creatures.',
        reviews1:'Raj:(This game is very good) 5 stars',
        reviews2:'Aishwariya:(Very nice game) 5 stars',
        reviews3:'Arjun:(needs bit of improvement) 4 stars',
        reviews4:'Vaishali:(Good game) 4 stars',
        video:'/videos/vid1.mp4',
        countInStock:12,
    },
    {
        _id:'4',
        name:' Among US',
        image:'/images/fg4.jpg',
        developer:'Developed By:Inner Sloth',
        category:"Top Free",
        price:0,
        buy:'BUY',
        ratings:4.4,
        description:'Among Us is a multiplayer game for four to ten players. ... All players except ghosts have a limited cone of vision, only allowing them to see other players within a certain unblocked distance around them. The Crewmates win by completing all tasks, or by identifying and eliminating all Impostors.',
        reviews1:'Raj:(This game is very good) 5 stars',
        reviews2:'Aishwariya:(Very nice game) 5 stars',
        reviews3:'Arjun:(needs bit of improvement) 4 stars',
        reviews4:'Vaishali:(Good game) 4 stars',
        video:'/videos/vid1.mp4',
        countInStock:1,
    },
    {
        _id:'5',
        name:' Paladins',
        image:'/images/fg2.jpg',
        developer:'Developed By:Hi-Rez Studios',
        category:"Top Free",
        price:0,
        buy:'BUY',
        ratings:4.5,
        description:'It is an Action packed multiplayer game with wide variety of weapons and fun to play maps,appealing graphics and breathtaking duels.',
        reviews1:'Raj:(This game is very good) 5 stars',
        reviews2:'Aishwariya:(Very nice game) 5 stars',
        reviews3:'Arjun:(needs bit of improvement) 4 stars',
        reviews4:'Vaishali:(Good game) 4 stars',
        video:'/videos/vid1.mp4',
        countInStock:5,
    },
    {
        _id:'6',
        name:' Warframe',
        image:'/images/fg6.jpg',
        developer:'Developed By:Digital Extremes',
        category:"Top Paid",
        price:30,
        buy:'BUY',
        description:'It is an Action packed multiplayer game with wide variety of weapons and fun to play maps,appealing graphics and breathtaking duels.',
        reviews1:'Raj:(This game is very good) 5 stars',
        reviews2:'Aishwariya:(Very nice game) 5 stars',
        reviews3:'Arjun:(needs bit of improvement) 4 stars',
        reviews4:'Vaishali:(Good game) 4 stars',
        video:'/videos/vid1.mp4',
        countInStock:1,
        
    },
    ]
}