export default  {
    Freegames:[
        {
        _id:'1',
        name:' Apex Legend',
        image:'/images/fg1.jpg',
        developer:'Developed By:Respawn Entertainment',
        price:0,
        category:"Top Free",
        buy:'BUY',
        ratings:4.5,
        description:'It is an Action packed multiplayer game with wide variety of weapons and fun to play maps,appealing graphics and breathtaking duels.',
        reviews1:'Raj:(This game is very good) 5 stars',
        reviews2:'Aishwariya:(Very nice game) 5 stars',
        reviews3:'Arjun:(needs bit of improvement) 4 stars',
        reviews4:'Vaishali:(Good game) 4 stars',
        video:'/videos/vid1.mp4',
        countInStock:6,
    },
    {   
        _id:'2',
        name:' COD Warzone',
        image:'/images/fg5.jpg',
        developer:'Developed By:Activision',
        category:"Top Free",
        price:40,
        buy:'BUY',
        ratings:4.6,
        description:'It is an Action packed multiplayer game with wide variety of weapons and fun to play maps,appealing graphics and breathtaking duels.',
        reviews1:'Raj:(This game is very good) 5 stars',
        reviews2:'Aishwariya:(Very nice game) 5 stars',
        reviews3:'Arjun:(needs bit of improvement) 4 stars',
        reviews4:'Vaishali:(Good game) 4 stars',
        video:'/videos/vid1.mp4',
        countInStock:3,
    },
    {
        _id:'3',
        name:' Minecraft',
        image:'/images/fg3.jpg',
        developer:'Developed By:Mojang Studios',
        category:"Top Free",
        price:20,
        buy:'BUY',
        ratings:4.3,
        description:'It is an Action packed multiplayer game with wide variety of weapons and fun to play maps,appealing graphics and breathtaking duels.',
        reviews1:'Raj:(This game is very good) 5 stars',
        reviews2:'Aishwariya:(Very nice game) 5 stars',
        reviews3:'Arjun:(needs bit of improvement) 4 stars',
        reviews4:'Vaishali:(Good game) 4 stars',
        video:'/videos/vid1.mp4',
        countInStock:12,
    },
    {
        _id:'4',
        name:' Among US',
        image:'/images/fg4.jpg',
        developer:'Developed By:Inner Sloth',
        category:"Top Free",
        price:0,
        buy:'BUY',
        ratings:4.4,
        description:'It is an Action packed multiplayer game with wide variety of weapons and fun to play maps,appealing graphics and breathtaking duels.',
        reviews1:'Raj:(This game is very good) 5 stars',
        reviews2:'Aishwariya:(Very nice game) 5 stars',
        reviews3:'Arjun:(needs bit of improvement) 4 stars',
        reviews4:'Vaishali:(Good game) 4 stars',
        video:'/videos/vid1.mp4',
        countInStock:1,
    },
    {
        _id:'5',
        name:' Paladins',
        image:'/images/fg2.jpg',
        developer:'Developed By:Hi-Rez Studios',
        category:"Top Free",
        price:0,
        buy:'BUY',
        ratings:4.5,
        description:'It is an Action packed multiplayer game with wide variety of weapons and fun to play maps,appealing graphics and breathtaking duels.',
        reviews1:'Raj:(This game is very good) 5 stars',
        reviews2:'Aishwariya:(Very nice game) 5 stars',
        reviews3:'Arjun:(needs bit of improvement) 4 stars',
        reviews4:'Vaishali:(Good game) 4 stars',
        video:'/videos/vid1.mp4',
        countInStock:5,
    },
    {
        _id:'6',
        name:' Warframe',
        image:'/images/fg6.jpg',
        developer:'Developed By:Digital Extremes',
        category:"Top Free",
        price:30,
        buy:'BUY',
        ratings:4.4,
        description:'It is an Action packed multiplayer game with wide variety of weapons and fun to play maps,appealing graphics and breathtaking duels.',
        reviews1:'Raj:(This game is very good) 5 stars',
        reviews2:'Aishwariya:(Very nice game) 5 stars',
        reviews3:'Arjun:(needs bit of improvement) 4 stars',
        reviews4:'Vaishali:(Good game) 4 stars',
        video:'/videos/vid1.mp4',
        countInStock:1,
        
    },
    {
        _id:'7',
        name:' Watch Dogs 2',
        image:'/images/fg10.jpg',
        developer:'Developed By:Digital Extremes',
        category:"Top Free",
        price:25,
        buy:'BUY',
        ratings:4.8,
        description:'It is an Action packed multiplayer game with wide variety of weapons and fun to play maps,appealing graphics and breathtaking duels.',
        reviews1:'Raj:(This game is very good) 5 stars',
        reviews2:'Aishwariya:(Very nice game) 5 stars',
        reviews3:'Arjun:(needs bit of improvement) 4 stars',
        reviews4:'Vaishali:(Good game) 4 stars',
        video:'/videos/vid1.mp4',
        countInStock:2,
        
    },
    {
        _id:'8',
        name:' Assasins-Creed valhalla',
        image:'/images/fg8.jpg',
        developer:'Developed By:Digital Extremes',
        category:"Top Free",
        price:60,
        buy:'BUY',
        ratings:4.3,
        description:'It is an Action packed multiplayer game with wide variety of weapons and fun to play maps,appealing graphics and breathtaking duels.',
        reviews1:'Raj:(This game is very good) 5 stars',
        reviews2:'Aishwariya:(Very nice game) 5 stars',
        reviews3:'Arjun:(needs bit of improvement) 4 stars',
        reviews4:'Vaishali:(Good game) 4 stars',
        video:'/videos/vid1.mp4',
        countInStock:1,
        
    },
    {
        _id:'9',
        name:' Witcher 3',
        image:'/images/fg9.jpg',
        developer:'Developed By:Digital Extremes',
        category:"Top Free",
        price:45,
        buy:'BUY',
        ratings:4.6,
        description:'It is an Action packed multiplayer game with wide variety of weapons and fun to play maps,appealing graphics and breathtaking duels.',
        reviews1:'Raj:(This game is very good) 5 stars',
        reviews2:'Aishwariya:(Very nice game) 5 stars',
        reviews3:'Arjun:(needs bit of improvement) 4 stars',
        reviews4:'Vaishali:(Good game) 4 stars',
        video:'/videos/vid1.mp4',
        countInStock:3,
        
    },
    {
        _id:'10',
        name:' Gta V',
        image:'/images/fg11.jpg',
        developer:'Developed By:Digital Extremes',
        category:"Top Free",
        price:0,
        buy:'BUY',
        ratings:4.5,
        description:'It is an Action packed multiplayer game with wide variety of weapons and fun to play maps,appealing graphics and breathtaking duels.',
        reviews1:'Raj:(This game is very good) 5 stars',
        reviews2:'Aishwariya:(Very nice game) 5 stars',
        reviews3:'Arjun:(needs bit of improvement) 4 stars',
        reviews4:'Vaishali:(Good game) 4 stars',
        video:'/videos/vid1.mp4',
        countInStock:5,
        
    },
    {
        _id:'11',
        name:' Forza Horizon 4',
        image:'/images/fg12.jpg',
        developer:'Developed By:Digital Extremes',
        category:"Top Free",
        price:35,
        buy:'BUY',
        ratings:4.6,
        description:'It is an Action packed multiplayer game with wide variety of weapons and fun to play maps,appealing graphics and breathtaking duels.',
        reviews1:'Raj:(This game is very good) 5 stars',
        reviews2:'Aishwariya:(Very nice game) 5 stars',
        reviews3:'Arjun:(needs bit of improvement) 4 stars',
        reviews4:'Vaishali:(Good game) 4 stars',
        video:'/videos/vid1.mp4',
        countInStock:4,
        
    },
    {
        _id:'12',
        name:' Rocket League',
        image:'/images/fg13.jpg',
        developer:'Developed By:Digital Extremes',
        category:"Top Free",
        price:0,
        buy:'BUY',
        ratings:4.3,
        description:'It is an Action packed multiplayer game with wide variety of weapons and fun to play maps,appealing graphics and breathtaking duels.',
        reviews1:'Raj:(This game is very good) 5 stars',
        reviews2:'Aishwariya:(Very nice game) 5 stars',
        reviews3:'Arjun:(needs bit of improvement) 4 stars',
        reviews4:'Vaishali:(Good game) 4 stars',
        video:'/videos/vid1.mp4',
        countInStock:1,
        
    }
    ]
}
