export const BORD_PAYMENT_REQUEST ='BORD_PAYMENT_REQUEST';
export const BORD_PAYMENT_SUCCESS ='BORD_PAYMENT_SUCCESS';
export const BORD_PAYMENT_FAIL ='BORD_PAYMENT_FAIL';

export const BORD_DETAILS_REQUEST ='BORD_DETAILS_REQUEST';
export const BORD_DETAILS_SUCCESS ='BORD_DETAILS_SUCCESS';
export const BORD_DETAILS_FAIL ='BORD_DETAILS_FAIL';