export const TOPFREE_LIST_REQUEST="TOPFREE_LIST_REQUEST";
export const TOPFREE_LIST_SUCCESS="TOPFREE_LIST_SUCCESS";
export const TOPFREE_LIST_FAIL="TOPFREE_LIST_FAIL";

export const FREEGAME_DETAILS_REQUEST="FREEGAME_DETAILS_REQUEST";
export const FREEGAME_DETAILS_SUCCESS="FREEGAME_DETAILS_SUCCESS";
export const FREEGAME_DETAILS_FAIL="FREEGAME_DETAILS_FAIL";

