export const TOPGAMES_LIST_REQUEST="TOPGAMES_LIST_REQUEST";
export const TOPGAMES_LIST_SUCCESS="TOPGAMES_LIST_SUCCESS";
export const TOPGAMES_LIST_FAIL="TOPGAMES_LIST_FAIL";

export const GAMEPLAY_DETAILS_REQUEST="GAMEPLAY_DETAILS_REQUEST";
export const GAMEPLAY_DETAILS_SUCCESS="GAMEPLAY_DETAILS_SUCCESS";
export const GAMEPLAY_DETAILS_FAIL="GAMEPLAY_DETAILS_FAIL";